apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: secure-vault-platform
  namespace: argocd
spec:
  description: Secure Vault Production Platform

  sourceRepos:
    - "https://github.com/amairiya/secure-vault-platform-gitops.git"
    - "https://helm.releases.hashicorp.com"

  destinations:
    - namespace: argocd
      server: https://kubernetes.default.svc
    - namespace: vault
      server: https://kubernetes.default.svc
    - namespace: monitoring
      server: https://kubernetes.default.svc

  clusterResourceWhitelist:
    - group: ""
      kind: Namespace

    - group: ""
      kind: PersistentVolume

    - group: rbac.authorization.k8s.io
      kind: ClusterRole

    - group: rbac.authorization.k8s.io
      kind: ClusterRoleBinding

    - group: storage.k8s.io
      kind: StorageClass

  orphanedResources:
    warn: true
    